services:
  eshopwebmvc:
    image: ${DOCKER_REGISTRY-}eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - "sqlserver"
    healthcheck:
      test: curl --fail http://localhost:5106/ || exit 1
      interval: 10s
      retries: 3
      timeout: 5s
    networks:
      - eshoponweb

  eshoppublicapi:
    image: ${DOCKER_REGISTRY-}eshoppublicapi
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
    depends_on:
      - "sqlserver"
    networks:
      - eshoponweb

  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y
    networks:
      - eshoponweb

  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "eshopwebmvc"
      - "eshoppublicapi"
      - "sqlserver"
    networks:
      - eshoponweb

networks:
  eshoponweb:
    name: eshoponweb

