name: Build Web Assets
description: 'Builds the web assets for the eShopOnWeb project'

inputs:
  dotnet-version:
    description: 'The version of the .Net Core SDK to use'
    required: true
    
runs:
  using: "composite"
  steps:

    - name: 'Set Dotnet Version ${{ inputs.dotnet-version }}'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install Dependencies
      shell: bash
      run: dotnet restore Everything.sln

    - name: Build Solution
      shell: bash
      run: dotnet build ./src/Web/Web.csproj --configuration Release --no-restore

    - name: Publish Web Assets
      shell: bash
      run:  |
        dotnet publish --property:PublishDir="${{ github.workspace }}/output" src/Web/Web.csproj

    - name: display contents of output directory
      shell: bash
      run: ls -R ${{ github.workspace }}/output

    - name: Publish Web Assets Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test_WebAssets
        path: ${{ github.workspace }}/output/wwwroot