name: Run Tests
description: 'Runs tests for the eShopOnWeb project using docker compose'

runs:
  using: "composite"
  steps:

    - name: Build docker images
      shell: bash
      run: docker compose build

    - name: Run docker compose up
      shell: bash
      run: |
        docker compose up -d
