name: Run Tests
description: 'Runs the test projects for the eShopOnWeb project'

inputs:
  dotnet-version:
    description: 'The version of the .Net Core SDK to use'
    required: true
  test-artifact-name:
    description: 'The name of the artifact to publish'
    required: true
  test-project-pattern:
    description: 'The pattern to use to find the test projects'
    required: true
  test-filter-criteria:
    description: 'The filter criteria to use to run the tests'
    required: false

runs:
  using: "composite"
  steps:

    - name: Download ${{ inputs.test-artifact-name }} Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.test-artifact-name }}
        path: ${{ github.workspace }}
        pattern: ${{ inputs.test-project-pattern }}

    # - name: Run ${{ inputs.test-artifact-name }} Tests
    #   shell: bash
    #   run: dotnet test --no-restore --no-build --verbosity normal ${{ inputs.test-project-pattern }}

    # - name: Run ${{ inputs.test-artifact-name }} Tests
    #   shell: pwsh
    #   run: powershell Invoke-WebRequest -Uri "https://localworker.blob.core.windows.net/win-x64/tests.zip" -OutFile "./tests.zip"
      
    # - name: Unzip tests binary
    #   shell: pwsh
    #   run: powershell Expand-Archive -Path tests.zip -DestinationPath ./

    # - name: Run tests
    #   uses: microsoft/vstest-action@v1.0.0
    #   with:
    #     searchFolder: ${{ inputs.test-project-pattern }}
    #     test-filter-criteria: ${{ inputs.test-filter-criteria }}
    #     runInParallel: true

    - name: Run Tests
      shell: bash
      run: dotnet test --no-restore --no-build --verbosity normal ${{ inputs.test-project-pattern }}
    
    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test_results
        path: TestResults

    

