name: Run Tests
description: 'Runs the test projects for the eShopOnWeb project'

inputs:
  dotnet-version:
    description: 'The version of the .Net Core SDK to use'
    required: true
  test-artifact-name:
    description: 'The name of the artifact to publish'
    required: true
  test-project-pattern:
    description: 'The pattern to use to find the test projects'
    required: true
  test-filter-criteria:
    description: 'The filter criteria to use to run the tests'
    required: false

runs:
  using: "composite"
  steps:

    - name: Download ${{ inputs.test-artifact-name }} Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.test-artifact-name }}
        path: artifacts
        pattern: ${{ inputs.test-project-pattern }}   

    # Issue with microsoft/vstest-action https://github.com/microsoft/vstest-action/issues/31
    # - name: Run tests
    #   uses: microsoft/vstest-action@v1.0.0
    #   with:
    #     searchFolder: ./tests/
    #     testAssembly: ${{ inputs.test-project-pattern }}
    #     runInParallel: true

    - name: Run Tests
      shell: bash
      run: dotnet test ./artifacts/tests/**/*Tests.dll
    
    - name: Publish Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test_results
        path: TestResults

    

