name: Build Solution
description: 'Builds the solution using the specified .Net Core SDK version'

inputs:
  dotnet-version:
    description: 'The version of the .Net Core SDK to use'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: 'Use .Net Core Sdk ${{ inputs.dotnet-version }}'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install Dependencies
      shell: bash
      run: dotnet restore Everything.sln

    - name: Build Solution
      shell: bash
      run: dotnet build Everything.sln --configuration Release --no-restore 