name: Build Test Projects
description: 'Builds the test projects for the eShopOnWeb project'

inputs:
  dotnet-version:
    description: 'The version of the .Net Core SDK to use'
    required: true
  artifact-name:
    description: 'The name of the artifact to publish'
    required: true
  project-pattern:
    description: 'The pattern to use to find the test projects'
    required: true
  
runs:
  using: "composite"
  steps:

    - name: 'Set Dotnet Version ${{ inputs.dotnet-version }}'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install Dependencies
      shell: bash
      run: dotnet restore Everything.sln

    - name: Build Solution
      shell: bash
      run: |
        dotnet build Everything.sln --configuration Release --no-restore

    # - name: Install PowerShell
    #   if: ${{ contains(inputs.project-pattern, 'InMemorySystemTests/InMemorySystemTests.csproj') }}
    #   shell: pwsh
    #   run: dotnet tool update --global PowerShell

    # - name: Ensure browsers are installed
    #   if: ${{ contains(inputs.project-pattern, 'InMemorySystemTests/InMemorySystemTests.csproj') }}
    #   shell: pwsh
    #   run: |
    #     pwsh  ${{ github.workspace }}/tests/InMemorySystemTests/bin/Release/net8.0/playwright.ps1 install --with-deps

    - name: Publish Test project
      shell: bash
      run:  |
        dotnet publish --property:PublishDir="${{ github.workspace }}/output" tests/${{ inputs.project-pattern }}

    # - name: Publish Playwright files
    #   if: ${{ contains(inputs.project-pattern, 'InMemorySystemTests/InMemorySystemTests.csproj') }}
    #   shell: bash
    #   run:  |
    #     dotnet publish --property:PublishDir="${{ github.workspace }}/playwright" tests/InMemorySystemTests/bin/Release/net8.0/.playwright

    # - name: Copy Playwright files
    #   if: ${{ contains(inputs.project-pattern, 'InMemorySystemTests/InMemorySystemTests.csproj') }}
    #   shell: bash
    #   run:  |
    #     cp -r ${{ github.workspace }}/tests/InMemorySystemTests/bin/Release/net8.0/.playwright ${{ github.workspace }}/output

    # - name: Publish Playwright artifacts
    #   if: ${{ contains(inputs.project-pattern, 'InMemorySystemTests/InMemorySystemTests.csproj') }}
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: playwright_files
    #     path: ${{ github.workspace }}/playwright
    #     retention-days: 1
    #     include-hidden-files: true
        
    - name: Publish ${{ inputs.artifact-name }} artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ github.workspace }}/output
        retention-days: 1