name: build-and-test

on:
  push:
    branches: [ "main" ]

jobs:
  build-solution:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-solution-action
        with:
          dotnet-version: 8.0.x