name: build-and-test

on:
  push:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '8.x'

jobs:
  build_solution:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Solution
        uses: ./.github/actions/build-solution-action
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

  build_web_assets:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Web Assets
        uses: ./.github/actions/build-web-assets-action
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

  build_tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Unit Tests
        uses: ./.github/actions/build-tests-action
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          artifact-name: tests_UnitTests
          project-pattern: |
             UnitTests\UnitTests.csproj
    
      - name: Build Integration Tests
        uses: ./.github/actions/build-tests-action
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          artifact-name: tests_IntegrationTests
          project-pattern: |
             IntegrationTests\IntegrationTests.csproj
      
      - name: Build Public Api Integration Tests
        uses: ./.github/actions/build-tests-action
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          artifact-name: tests_PublicApiIntegrationTests
          project-pattern: |
            PublicApiIntegrationTests\PublicApiIntegrationTests.csproj

      - name: Build Functional Tests
        uses: ./.github/actions/build-tests-action
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          artifact-name: tests_FunctionalTests
          project-pattern: |
            FunctionalTests\FunctionalTests.csproj

  run_tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    needs: [ build_solution, build_tests, build_web_assets ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Unit Tests
        uses: ./.github/actions/run-tests-action
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          test-artifact-name: tests_UnitTests
          test-project-pattern: |
            UnitTests/**/*
          test-filter-criteria: ""

      - name: Run Integration Tests
        uses: ./.github/actions/run-tests-action
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          test-artifact-name: tests_IntegrationTests
          test-project-pattern: |
             IntegrationTests/**/*
             PublicApiIntegrationTests/**/*
          test-filter-criteria: ""

      - name: Run Public Api Integration Tests
        uses: ./.github/actions/run-tests-action
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          test-artifact-name: tests_PublicApiIntegrationTests
          test-project-pattern: |
            PublicApiIntegrationTests/**/*
          test-filter-criteria: ""

      - name: Run Functional Tests
        uses: ./.github/actions/run-tests-action
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          test-artifact-name: tests_FunctionalTests
          test-project-pattern: |
             FunctionalTests/**/*
          test-filter-criteria: ""

