name: build-and-test

on:
  push:
    branches: [ "main" ]

jobs:
  build_solution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Solution
        uses: ./.github/actions/build-solution-action
        with:
          dotnet-version: 8.0.x