name: Deploy Bicep file
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: infra/main.bicep
        parameters: |
          environmentName=$${{ variables.ENVIRONMENT }}
          location=${{ variables.LOCATION }}
          resourceGroupName=${{ secrets.AZURE_RG }}
          vmUserPassword=${{ variables.VM_USER_PASSWORD }}
          agentPat=${{ secrets.AGENT_PAT }}
          agentPool= ${{ variables.AGENT_POOL }}
          principalId=${{ secrets.PRINCIPAL_ID }}
          sqlAdminPassword=${{ secrets.SQL_ADMIN_PASSWORD }}      
        failOnStdErr: false